---
Formação Cientista de Dados - Prof. Fernando Amaral
Gráficos Básicos
---
Histograma
```{r}
trees
hist( trees$Height)
hist( trees$Height,  main="Árvores", ylab="Frequência",xlab="Altura", col="blue")
hist( trees$Height,  main="Árvores", ylab="Frequência",xlab="Altura", col="blue",
      density=20, breaks=20    )
```
Densidade
```{r}
densidade = density(trees$Height)
plot(densidade)
```
Densidade sobre o Histograma, parâmetro par
```{r}
#Executar com ctrl+shift+enter----EXECUTAR AS 3 LINHAS SIMULTANEAMENTE
hist(trees$Height, main=NULL, xlab=NULL, ylab = NULL)
#EVITA SOBREPOSICOES
par(new=TRUE)
plot(densidade)
```
Dispersão
```{r}
plot(trees$Girth, trees$Volume)
plot(trees$Girth, trees$Volume, main="Árvores")
plot(trees$Girth, trees$Volume, ylab="Cirunferência", xlab="Volume", col="blue", main="Árvores")
#pch muda o elementog gráfico
plot(trees$Girth, trees$Volume, ylab="Cirunferência", xlab="Volume", col="blue", main="Árvores", pch=20)
#PCH MUDA O ELEMENTO grafico 2=triangulo
```
Muda tipo
```{r}
plot(trees$Girth, trees$Volume, ylab="Cirunferência", xlab="Volume", col="blue", main="Árovres", pch=20, type="l")
#type l = linhas
```
Tremulação, diminui sobreposição
```{r}
plot(jitter(trees$Girth), trees$Volume, ylab="Cirunferência", xlab="Volume", col="blue", main="Árvores")
```
Legenda com dimensão categórica
```{r}
plot(CO2$conc, CO2$uptake,pch=20, col= CO2$Treatment)
#"bottom", "bottomleft", "left", "topleft", "top", "topright", "right" and "center"
legend("bottomright",legend=c("nonchilled","chilled"),cex=1, fill=c("black","red")) 
```
Novos dados
```{r}
plot(trees)
#cria matriz de gráficos com as categorias
```
Divisão da tela
```{r}
#Executar com crtl+shift+enter
split.screen(figs=c(2,2))
#divisao de 4 locais de impressão
#apontando o que será impresso e onde
screen(1)
plot(trees$Girth, trees$Volume)
screen(2)
plot(trees$Girth, trees$Height)
screen(3)
plot(trees$Height, trees$Volume)
screen(4)
hist(trees$Volume)
close.screen(all=TRUE)
```

